services:
  ahorroland-api:
    image: sergioizqdev/ahorroland-backend:${API_VERSION:-latest}
    container_name: ahorroland-api
    ports:
      - "8080:80"
      - "8443:443" # Descomentar si usas HTTPS dentro del contenedor, usualmente el proxy inverso (Nginx/Traefik) maneja SSL
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      
      # --- Base de Datos ---
      # Nota: En Docker usamos el nombre del servicio 'db' y el puerto interno 3306
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=${DB_DATABASE};Uid=${DB_USER};Password=${DB_PASSWORD};GuidFormat=Binary16;Allow User Variables=true;

      # --- JWT Security ---
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - JwtSettings__Issuer=${JWT_ISSUER:-AhorroLand}
      - JwtSettings__Audience=${JWT_AUDIENCE:-AhorroLand}
      - JwtSettings__ExpirationMinutes=${JWT_EXPIRATION:-720}

      # --- Email Settings (Brevo) ---
      - EmailSettings__SmtpServer=${EMAIL_SMTP_SERVER}
      - EmailSettings__SmtpPort=${EMAIL_SMTP_PORT}
      - EmailSettings__SmtpUser=${EMAIL_SMTP_USER}
      - EmailSettings__SmtpPass=${EMAIL_SMTP_PASS}
      - EmailSettings__FromEmail=${EMAIL_FROM_EMAIL}
      - EmailSettings__FromName=${EMAIL_FROM_NAME:-AhorroLand}
      - EmailSettings__EnableSsl=${EMAIL_ENABLE_SSL:-true}

      # --- Logging (.NET 10 + HtmlFileLog + Serilog) ---
      - Serilog__MinimumLevel__Default=Information
      # Configuración para tu sistema HtmlFileLog
      - HtmlFileLog__LogDirectory=/app/logs
      - HtmlFileLog__FileNamePrefix=ahorroland-prod
      - HtmlFileLog__RetainedFileCountLimit=7
      - HtmlFileLog__CleanOnStartup=false
      
    volumes:
      # Logs: Mapeamos la carpeta del host a la carpeta configurada arriba
      - ./logs/backend:/app/logs
      
      # Persistencia de Avatares / Archivos estáticos
      - /var/www/ahorroland/storage/avatars:/app/wwwroot/avatars

    networks:
      - ahorroland-red
    depends_on:
          db:
            condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  frontend:
    container_name: ahorroland-frontend
    image: sergioizqdev/ahorroland-frontend:${FRONTEND_VERSION:-latest}
    restart: unless-stopped
    ports:
      - "3001:80"
    networks:
      - ahorroland-red

  logrotate:
    image: blacklabelops/logrotate:latest
    container_name: ahorroland-logrotate
    restart: unless-stopped
    environment:
      - "LOGS_DIRECTORIES=/logs"
      - "LOGROTATE_INTERVAL=daily"
      - "LOGROTATE_COPIES=7"
      - "LOGROTATE_SIZE=10M"
      - "LOGROTATE_COMPRESSION=compress"
    volumes:
      - ./logs:/logs
    networks:
      - ahorroland-red